### PR TITLE
French translations and fixes

### PR DESCRIPTION
**Pull request by frank-zago**
Re-introduit SETUP_AUTOPLAY_AI_BASE, SETUP_AUTOPLAY_AI_MODNAR, SETUP_AUTOPLAY_AI_XILMI et SETUP_GAME_DIFFICULTY_HELP qui avaient été enlevés par erreur.

### CODE REVIEW

**Comment by BrokenRegistry** [comment]
Good.
I'm now working to make the Governor panel translatable... (All text are now hard coded by the Graphic panel generation tool)
So I'll suggest you to not change the GOVERNOR_* labels.
I'll also try to make a tools to apply (almost) immediately the change in the text file.

**Comment by BrokenRegistry** [comment]
You may already know that if you place a "lang" folder next to the jar file, its content will take priority. You don't need to fill it with all the files, just the ones you want to edit, and they should be placed in their corresponding subfolder. (ex: lang/en/labels.txt; lang/en/races/Darlok.dialogue.txt)
They will be read when the application starts, and when changing languages.
Now they can also be quickly reloaded with "Alt-L"
- When the help is displayed ("F1" or "Shift-F1")
- When you are in the options panels (the brown ones)
- In the initial Species and Galaxy configuration panels.
- In the Governor panel.
- A beep will validate the action.
You may need to hover over the text, or change the parameter value to force a screen refresh and see the effect... If that's not enough, exit the panel and come back.
You may need to hover over the text, or change the parameter value to force a screen refresh and see the effect... If that's not enough, exit the panel and come back.
For the governor panel, changing its size (+/- 1%) will refresh it (I still don't understand why this is necessary)
I'm still working on the governor panel, as wrong text length can disrupt the panel.

**Comment by frank-zago** [comment]
Thanks. That's indeed better than rebuilding the jar file.

**Comment by BrokenRegistry** [comment]
Added "Alt-L" language refresh function to most small panels without access to "Help".
(While debugging I added and removed these calls! I guess I might as well leave them available all the time.)
Not all of them have been tested (but it should be safe since the call is standard).
Let me know if you found an isolated panel without this function.

**Pull request merged**
